url: http://hepaestus.com
baseurl: "/3d-printing/"
owner: "Pete Olsen III"
timezone: America/New_York
title: "3D Printing Manifesto"
sub-title: "Always Be Printing"
description: "In an effort to help others, I am posting my 3d printing experiences, failures, and successes."
logo: assets/img/pete_logo.png
email: "hepaestus@gmail.com"
blank_title: false
favicon: true
show_downloads: false
google_analytics: G-PHFZS8L51S
remote_theme: BDHU/minimalist
color-scheme: dark
excerpt_separator: <!--more-->
whitelist: [jekyll-analytics]
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme
  - jekyll-analytics
